// client/src/routes/login/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { login, loginWithGoogle } from '$lib/auth/login';
    import { t } from '$lib/i18n';
    import FormInput from '$lib/components/FormInput.svelte';

    let email = $state('');
    let password = $state('');
    let error = $state('');
    let loading = $state(false);
    let showPassword = $state(false);

    async function handleSubmit() {
        loading = true;
        error = '';

        const result = await login(email, password);

        if (result.success) {
            goto('/dashboard');
        } else {
            error = result.error ?? $t('auth.login.failed');
        }
        loading = false;
    }

    async function handleGoogleLogin() {
        loading = true;
        error = '';

        const result = await loginWithGoogle();

        if (result.success) {
            goto('/dashboard');
        } else {
            error = result.error ?? $t('auth.google.failed');
        }
        loading = false;
    }
</script>

<svelte:head>
    <title>{$t('auth.signin')} | {$t('app.name')}</title>
</svelte:head>

<div class="flex min-h-screen items-center justify-center bg-neutral-50">
    <div class="w-full max-w-sm space-y-6 rounded-lg bg-white p-8 shadow-md border border-neutral-200">
        <h1 class="text-2xl font-bold text-center text-neutral-800">{$t('auth.signin')}</h1>

        {#if error}
            <p class="rounded bg-red-100 p-3 text-red-700 text-sm">{error}</p>
        {/if}

        <form onsubmit={handleSubmit} class="space-y-4">
            <FormInput id="email" label={$t('auth.email')} type="email" bind:value={email} />
            
            <div class="relative">
                <FormInput 
                    id="password" 
                    label={$t('auth.password')} 
                    type={showPassword ? 'text' : 'password'} 
                    bind:value={password} 
                />
                <button
                    type="button"
                    onclick={() => showPassword = !showPassword}
                    class="absolute right-3 top-9.5 text-neutral-500 hover:text-neutral-700 focus:outline-none focus:text-neutral-700 transition-colors"
                    aria-label={showPassword ? 'Hide password' : 'Show password'}
                >
                    {#if showPassword}
                        <!-- Eye slash icon (hide) -->
                        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                        </svg>
                    {:else}
                        <!-- Eye icon (show) -->
                        <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                        </svg>
                    {/if}
                </button>
            </div>

            <button
                type="submit"
                disabled={loading}
                class="w-full rounded bg-brand-500 py-2.5 text-white font-medium hover:bg-brand-600 disabled:opacity-50 transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
            >
                {loading ? $t('auth.signin.loading') : $t('auth.signin')}
            </button>
        </form>

        <div class="relative">
            <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-neutral-300"></div>
            </div>
            <div class="relative flex justify-center text-sm">
                <span class="bg-white px-2 text-neutral-500">{$t('auth.or')}</span>
            </div>
        </div>

        <button
            onclick={handleGoogleLogin}
            disabled={loading}
            class="flex w-full items-center justify-center gap-3 rounded border border-neutral-300 bg-white py-2.5 text-neutral-700 font-medium hover:bg-neutral-50 disabled:opacity-50 transition-colors focus:outline-none focus:ring-2 focus:ring-neutral-400 focus:ring-offset-2"
        >
            <svg class="h-5 w-5" viewBox="0 0 24 24">
                <path
                    fill="#4285F4"
                    d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                />
                <path
                    fill="#34A853"
                    d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                />
                <path
                    fill="#FBBC05"
                    d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                />
                <path
                    fill="#EA4335"
                    d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                />
            </svg>
            {$t('auth.continue.google')}
        </button>
    </div>
</div>

// apps/client/src/pages/Login.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { EyeIcon, EyeSlashIcon } from '@heroicons/react/24/outline';
import { useAuth } from '../contexts/AuthContext';
import { Card, FormInput, Button } from '../components/ui';

export default function Login() {
  const { t } = useTranslation();
  const { login, signInWithGoogle } = useAuth();  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      const signedIn = await login(email, password);
      // A pending user has no permissions, so send them to the waiting room
      // rather than the dashboard, which would only show errors.
      navigate(signedIn.role === 'pending' ? '/pending' : '/dashboard');
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Login failed';
      if (message.includes('suspended')) {
        setError(t('auth.accountSuspended'));
      } else {
        setError(message);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleSignIn = async () => {
    setError('');
    setGoogleLoading(true);

    try {
      // On success this navigates away to Google, so the loading state is
      // intentionally left set — clearing it would flash the button back.
      await signInWithGoogle();
    } catch (err) {
      setError(err instanceof Error ? err.message : t('auth.googleSignInFailed'));
      setGoogleLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-bg-canvas py-12 px-4 sm:px-6 lg:px-8">
      <Card className="max-w-md w-full" padding="lg">
        <div className="space-y-6">
          <div>
            <h2 className="text-center text-2xl font-medium text-text-primary">
              {t('auth.loginTitle')}
            </h2>
          </div>
          <form className="space-y-4" onSubmit={handleSubmit}>
            {error && (
              <div className="rounded-[var(--radius-control)] bg-status-delayed-bg p-4">
                <p className="text-sm text-status-delayed-text">{error}</p>
              </div>
            )}
            <FormInput
              label={t('auth.email')}
              id="email"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder={t('auth.email')}
            />
            <div className="relative">
              <FormInput
                label={t('auth.password')}
                id="password"
                type={showPassword ? 'text' : 'password'}
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder={t('auth.password')}
                className="pr-10"
              />
              <button
                type="button"
                onClick={() => setShowPassword((prev) => !prev)}
                aria-label={showPassword ? t('auth.hidePassword') : t('auth.showPassword')}
                className="absolute right-3 top-9.5 text-text-secondary hover:text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/50 rounded-(--radius-control) p-0.5"
              >
                {showPassword ? (
                  <EyeSlashIcon className="h-5 w-5" />
                ) : (
                  <EyeIcon className="h-5 w-5" />
                )}
              </button>
            </div>
            <Button
              type="submit"
              disabled={loading}
              loading={loading}
              className="w-full"
            >
              {t('auth.login')}
            </Button>
          </form>

          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-border-default" />
            </div>
            <div className="relative flex justify-center text-sm">
              <span className="px-2 bg-bg-surface text-text-secondary">{t('auth.orDivider')}</span>
            </div>
          </div>

          <Button
            type="button"
            variant="secondary"
            onClick={handleGoogleSignIn}
            loading={googleLoading}
            disabled={googleLoading}
            className="w-full"
          >
            <svg className="w-5 h-5 mr-2" viewBox="0 0 24 24">
              <path
                fill="#4285F4"
                d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
              />
              <path
                fill="#34A853"
                d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
              />
              <path
                fill="#FBBC05"
                d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
              />
              <path
                fill="#EA4335"
                d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
              />
            </svg>
            {t('auth.signInWithGoogle')}
          </Button>

          <div className="text-center">
            <p className="text-sm text-text-secondary">
              {t('auth.contactAdmin')}
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
